Array Concept & Concept Exercise
exercism/common-lisp pull request #422
Opened 2021-07-05 20:50 UTC by verdammelt

This PR adds array concept files and concept exercise. 

It also includes a vector concept which is also part of the concept exercise. It seemed to be a good thing to have a separate concept for vectors.

The concept & exercise skips a lot of the details of arrays such as fill pointers, adjustable arrays etc. Those can be dealt with in later concepts and exercises.

2021-07-05 20:54 UTC, verdammelt commented
@TheLostLambda not done yet - but at least rough draft of concepts. Would love any feedback.

2021-07-11 09:38 UTC, TheLostLambda commented
I may be a touch tied up today and tomorrow, but will give this a proper look quite soon!

2021-08-02 03:21 UTC, verdammelt commented
@TheLostLambda If you have time I'd like your review of this.

I'm not in love with it - but want to get *something* in as an `array` concept/exercise. Our `sameness` concept's exercise depends upon it.

If you don't have time that's fine too... no pressure.

2021-08-02 06:31 UTC, TheLostLambda commented
Hi @verdammelt ! I'll plan on giving it a review today or tomorrow! I agree it's pretty important to have as a dependency :)

2021-08-03 13:38 UTC, TheLostLambda requested changes
Overall this is looking quite good! My biggest two bits of feedback would be:

1. I think we could trim down the `introduction.md` files and then add a bit more to the `after.md` ones. Right now it seems as if they are a bit swapped. I think `after.md` should always contain everything that the introduction does plus a bit more.
2. We would probably benefit from some more short code-snippets. They are usually helpful in the `instructions.md` and are currently missing from the `after.md`s.

I like how this actually addresses the multi-dimensionality of arrays! I find it a more meaningful difference from lists than just explaining the different in-memory data structures :)

Thanks for all of the hard work and let me know what you think!

2021-08-03 13:38 UTC, TheLostLambda commented on concepts/arrays/about.md
>  # About
We should probably include some syntax examples in this file :) We want to be sure that all of the information from the concept's `introduction.md` ends up here.

Once upon a time I was rather bothered by needing to "duplicate" information from the introduction, but [the most recent docs](https://github.com/exercism/docs/blob/main/building/tracks/concepts.md) which I took a look at today have swayed me I think. The introduction file gets fully replaced by this one (as I understand), so we want to be sure that the student isn't losing any information in that process.

I think we should as least carry over your nice syntax examples :)

2021-08-03 13:38 UTC, TheLostLambda commented on concepts/arrays/about.md
> +It also can take arguments to define the values to initialize the array with.
After this, for example, would be a good place for example code snippets :)

2021-08-03 13:38 UTC, TheLostLambda commented on concepts/arrays/about.md
> +An element can also be accessed with `row-major-aref` which takes a single integer specifying the element in []row-major order][row-major-order].
The markdown for this link is a little mangled here

2021-08-03 13:38 UTC, TheLostLambda commented on concepts/arrays/about.md
> +* `array-total-size` to get total number of elements in the array.
Perhaps also a good place for some simple code examples :)

2021-08-03 13:38 UTC, TheLostLambda commented on concepts/vectors/.meta/config.json
> +  "blurb": "An vector is a 1-dimensional array.",
Could probably be "A vector..." here :)

2021-08-03 13:38 UTC, TheLostLambda commented on concepts/vectors/about.md
> +To access elements of a vector use `aref`, the indexes are zero-based:
This line ends with a colon and some empty lines – is something more supposed to be here?

2021-08-03 13:38 UTC, TheLostLambda commented on concepts/vectors/about.md
> +# About
Similar feedback to the files for arrays, right now the `introduction.md` is bigger than the `after.md`, but I think that should be the other way around. I think the `introduction.md` is supposed to be the bare minimum and `after.md` the place for elaboration and other helpful functions

2021-08-03 13:38 UTC, TheLostLambda commented on exercises/concept/larrys-winning-checker/.docs/instructions.md
> +All the cells of the board should be `NIL`.
Might be worth tossing in a code example of the function here and under the other headings in this file that don't currently have one. At the moment it's a touch ambiguous if this function takes any arguments, for example.

2021-08-03 13:38 UTC, TheLostLambda commented on exercises/concept/larrys-winning-checker/.docs/instructions.md
> +The function `column` will take a board and a column number and should return an array of the elements in that row.
Should probably end with "in that column." instead :) Examples for all of these would be good!

2021-08-03 13:38 UTC, TheLostLambda commented on exercises/concept/larrys-winning-checker/.docs/introduction.md
> +(array-in-bounds-p #2A((1) (2)) 0 1) ; => T
Things like this could probably be saved for the `after.md`, since they don't seem vital to the exercise

2021-08-03 13:38 UTC, TheLostLambda commented on exercises/concept/larrys-winning-checker/.docs/introduction.md
> +(make-array '(3 3 3)
This last 3D array is a bit big. It could be saved for the `after.md`? But I'm not too fussed about it staying here either :)

2021-08-03 13:38 UTC, TheLostLambda commented on exercises/concept/larrys-winning-checker/.docs/introduction.md
> +To deterine if an object is an array one can use `arrayp`.
This is useful, but perhaps not vital in an introduction. Maybe `after.md` material?

2021-08-03 13:38 UTC, TheLostLambda commented on exercises/concept/larrys-winning-checker/.meta/exemplar.lisp
> +  (and (eq (aref row-or-col 0)
A nice, concise trick I found could be something like `(every #'eq row-or-col (subseq row-or-col 1))`, but that might be a bit too tricky for this early concept. It would be nice to mention in the `after.md` as an alternative if a student finds this solution verbose.

2021-08-03 13:38 UTC, TheLostLambda commented on exercises/concept/larrys-winning-checker/.meta/exemplar.lisp
> +  (make-array 3 :initial-contents (list
I assume this concept comes before things like iteration or mapping?

2021-08-04 00:43 UTC, verdammelt commented on concepts/arrays/.meta/config.json
> +  "blurb": "An array is a sequence of elements which can be referred to by integral indexes. They can be multi-dimensional. They can contain hetergeneous data.",
done!

hetergeneous is def. not a word... i guess i don't have a spell checker running on JSON files... or i added it to the local dictionary at some point! :D

2021-08-04 00:44 UTC, verdammelt commented on concepts/arrays/about.md
> +In Common Lisp like other languages an array is a set of elements which are accessed via integral indexes.
punctuation is for the WEAK!

but yet... sounds great.

2021-08-04 00:47 UTC, verdammelt commented on concepts/vectors/about.md
> +To access elements of a vector use `aref`, the indexes are zero-based:
lol probably... [sigh]

2021-08-04 00:49 UTC, verdammelt commented on exercises/concept/larrys-winning-checker/.meta/exemplar.lisp
> +  (and (eq (aref row-or-col 0)
I did keep this simple because we haven't actually taught `eq` yet. But I'm bending the rules and telling the student that it is the thing to use. Sort of a chicken-and-egg problem.

But I like putting a fancier version in after.md - but we def. haven't taught them things like `every` and i don't even know what concept that could be taught in! [head swimming]

2021-08-04 00:50 UTC, verdammelt commented on exercises/concept/larrys-winning-checker/.meta/exemplar.lisp
> +  (make-array 3 :initial-contents (list
yes it does... so i kept things very simple. I tried to keep the example file to things that are known to have already been taught. Should write this down in sort of 'style guide' i guess.

2021-08-04 00:52 UTC, verdammelt commented
@TheLostLambda thanks for the feedback - I'm going to knock off some 'small stuff' first then start handling the larger parts.

2021-08-05 00:53 UTC, verdammelt commented on concepts/vectors/about.md
> +# About
hopefully fixing this by starting with making about.md == introduction.md then adding a few extra bits.

2021-08-05 00:54 UTC, verdammelt commented on concepts/vectors/about.md
> +To access elements of a vector use `aref`, the indexes are zero-based:
There was a code example there. Not sure why you could not see it.

2021-08-05 11:55 UTC, verdammelt commented
@TheLostLambda I think i adressed your issues - let me know what you think.

2021-08-07 09:51 UTC, TheLostLambda commented
Sorry for the delay, I'll give things a second pass today!

2021-08-08 10:50 UTC, TheLostLambda approved these changes
I think the `instructions.md` could use one of those code examples for every function the student needs to define, but aside from that, this is looking great!

Happy to merge once we have some examples there :) (Unless of you have a particular reason for avoiding them)

2021-08-08 10:50 UTC, TheLostLambda commented on exercises/concept/larrys-winning-checker/.docs/instructions.md
>  ## 2. Starting from an existing board
Headings 3, 4, and 5 could also use those syntax examples that you added to 1 if you're up for it :)

2021-08-08 16:08 UTC, verdammelt commented on exercises/concept/larrys-winning-checker/.docs/instructions.md
>  ## 2. Starting from an existing board
Thanks for catching these.

2021-08-08 16:11 UTC, merged