Add documentation about what the representer does.
exercism/common-lisp pull request #670
Opened 2022-10-10 22:47 UTC by verdammelt

This information is shown in the track's documentation pages and, more
importantly, the summary is shown to the mentor writing
representations.

2022-10-11 01:23 UTC, kotp reviewed
Did you write the documentation, or is it coming in from somewhere else?

If it is coming from somewhere else, then we should request changes be made there, to benefit all the tracks, but if this is original material, we should make corrections there.

Line 3, `uses` instead of `use`, for example, and some other things I did not yet write, since if it can be at the source, it would be better.

2022-10-11 08:12 UTC, ErikSchierboom approved these changes
Excellent!

2022-10-11 08:12 UTC, ErikSchierboom commented on docs/config.json
> +        {
Just in case you care:

```suggestion
    {
```

2022-10-11 12:38 UTC, verdammelt commented on docs/config.json
> +        {
Thanks.

2022-10-11 12:40 UTC, verdammelt commented
> Did you write the documentation, or is it coming in from somewhere else?

I wrote these following the example of the F# track's representer documentation. So there is no other source of these documents.
 
> Line 3, `uses` instead of `use`, for example, and some other things I did not yet write, since if it can be at the source, it would be better.

Thank you for catching that. I'll fix that for sure. Any other issues?

2022-10-11 12:42 UTC, verdammelt reviewed
Quick wording fix.

2022-10-11 12:42 UTC, verdammelt commented on docs/REPRESENTER_NORMALIZATIONS.md
> +The [representer][representer] use `[read][cl-read]` to read the submission and `[write][cl-write]` to write the representation as well as applying some additional normalizations.
```suggestion
The [representer][representer] uses `[read][cl-read]` to read the submission and `[write][cl-write]` to write the representation as well as applying some additional normalizations.
```

2022-10-11 12:42 UTC, verdammelt commented on exercises/shared/.docs/representations.md
> +The [representer][representer] use `[read][cl-read]` to read the submission and `[write][cl-write]` to write the representation as well as applying some additional normalizations.
```suggestion
The [representer][representer] uses `[read][cl-read]` to read the submission and `[write][cl-write]` to write the representation as well as applying some additional normalizations.
```

2022-10-11 18:38 UTC, kotp requested changes

2022-10-11 18:38 UTC, kotp commented on docs/REPRESENTER_NORMALIZATIONS.md
> +Instead of normalizing any names which may be present in the documentation string the string is removed.
There seems to be a comma missing from here, with the prepositional phrase.

I would place the comma(s) but, depending on where I place them, the meaning can change.

2022-10-11 18:38 UTC, kotp commented on docs/REPRESENTER_NORMALIZATIONS.md
> +The submission is `[read][cl-read]` in and so all comments are removed.
I am not sure what is being said here, but it might be:

Maybe it is telling me:

```suggestion
The submission is `[read][cl-read]` in, which removes all comments.
```

2022-10-11 18:38 UTC, kotp commented on docs/REPRESENTER_NORMALIZATIONS.md
> +The submission is `[read][cl-read]` in and so all symbols are normalized to uppercase.
The same here, confusion the "and so".

Maybe:

```suggestion
The submission is `[read][cl-read]` in which normalizes symbols to uppercase.
```

2022-10-11 18:38 UTC, kotp commented on exercises/shared/.docs/representations.md
> +The [representer][representer] uses `[read][cl-read]` to read the submission and `[write][cl-write]` to write the representation as well as applying some additional normalizations.
Comma before `as well as`, I think:

```suggestion
The [representer][representer] uses `[read][cl-read]` to read the submission and `[write][cl-write]` to write the representation, as well as applying some additional normalizations.
```

2022-10-11 18:38 UTC, kotp commented on exercises/shared/.docs/representations.md
> +In total each submission has the following normalizations applied to it:
```suggestion
In total, each submission has the following normalizations applied to it:
```

We could also state:

```suggestion
Each submission has the following normalizations applied to it:
```

2022-10-11 18:39 UTC, kotp commented on docs/REPRESENTER_NORMALIZATIONS.md
> +Instead of normalizing any names which may be present in the documentation string the string is removed.
Also, why is this file name capitalized compared to other file names?

2022-10-12 14:04 UTC, ErikSchierboom commented on docs/REPRESENTER_NORMALIZATIONS.md
> +Instead of normalizing any names which may be present in the documentation string the string is removed.
> Also, why is this file name capitalized compared to other file names?

Because all the files within the `docs` directory are capitalized.

2022-10-12 17:37 UTC, kotp commented on docs/REPRESENTER_NORMALIZATIONS.md
> +Instead of normalizing any names which may be present in the documentation string the string is removed.
Since this is a multi-platform system, should we avoid doing this?  On some platforms case matters, while on others it does not.

2022-10-13 00:23 UTC, verdammelt commented
Thank you @kotp for your suggestions. I've tried to integrate them.

2022-10-13 00:24 UTC, verdammelt commented on exercises/shared/.docs/representations.md
> +In total each submission has the following normalizations applied to it:
I applied the latter change.

2022-10-13 00:24 UTC, verdammelt commented on exercises/shared/.docs/representations.md
> +The [representer][representer] uses `[read][cl-read]` to read the submission and `[write][cl-write]` to write the representation as well as applying some additional normalizations.
Thanks.

2022-10-13 00:25 UTC, verdammelt commented on docs/REPRESENTER_NORMALIZATIONS.md
> +The submission is `[read][cl-read]` in and so all symbols are normalized to uppercase.
I have reworded the sentence- hopefully makes more sense (but does assume a little understanding of `read` which seems reasonable for a document targeting mentors in this language)

2022-10-13 00:25 UTC, verdammelt commented on docs/REPRESENTER_NORMALIZATIONS.md
> +The submission is `[read][cl-read]` in and so all comments are removed.
I have reworded the sentence- hopefully makes more sense (but does assume a little understanding of `read` which seems reasonable for a document targeting mentors in this language)

2022-10-13 01:32 UTC, kotp approved these changes
Nice.

2022-10-13 13:40 UTC, merged