yacht: add exercise
exercism/common-lisp pull request #807
Opened 2024-04-22 16:38 UTC by SimaDovakin

## Summary

For #48in24. I used the Clojure implementation as a reference.

## Checklist
- [ ] If docs where changed run `./bin/configlet generate` to ensure all documents are properly generated.
- [ ] CI is green

2024-05-13 15:34 UTC, SimaDovakin commented
@verdammelt Hi! Could we merge it, or should I change something?

2024-05-14 01:06 UTC, verdammelt requested changes
I think this is a good start... but I would like to discuss some small changes to make it, IMHO, better.

2024-05-14 01:06 UTC, verdammelt commented on exercises/practice/yacht/.meta/example.lisp
> +                  (if freq
Just a thought, and maybe I'm wrong. But what if instead of checking if `freq` is `nil` why not use a default of `0` for `gethash` so we can always do `(incf (gethash n acc 0))`.

2024-05-14 01:06 UTC, verdammelt commented on exercises/practice/yacht/.meta/example.lisp
> +              (if (>= val 4)
How about `when`?

2024-05-14 01:06 UTC, verdammelt commented on exercises/practice/yacht/.meta/example.lisp
> +        ((equal category "four of a kind") (let ((dice (four-of-a-kind-dice (frequencies scores))))
Why does `full-house?` take the scores but `four-of-a-kind-dice` take frequencies? Might be better to have consistent interface for these functions.

2024-05-14 01:06 UTC, verdammelt commented
> @verdammelt Hi! Could we merge it, or should I change something?

Sorry it took me so long to respond. But see my comments above.

2024-05-14 06:22 UTC, SimaDovakin commented
@verdammelt Thank you for review. I will improve my solution.

2024-05-21 09:24 UTC, SimaDovakin commented
@verdammelt Is it ok now?

2024-05-25 22:58 UTC, verdammelt reviewed
I think this is looking good, but using keywords rather than strings would be better.

2024-05-25 22:58 UTC, verdammelt commented on exercises/practice/yacht/.meta/example.lisp
> +  (cond ((equal category "ones") (count 1 scores))
I think using keywords rather than strings would be more "lispy"

(I thought I had left this comment originally but it seems I had not - my apologies)

2024-05-26 07:02 UTC, SimaDovakin commented on exercises/practice/yacht/.meta/example.lisp
> +  (cond ((equal category "ones") (count 1 scores))
Am I right @verdammelt? I should use instead of categories as strings (e.g., "ones", "twos"), categories as keywords (e.g., :ones, :twos).

2024-05-26 15:07 UTC, verdammelt commented on exercises/practice/yacht/.meta/example.lisp
> +  (cond ((equal category "ones") (count 1 scores))
Yes, I believe that for this sort of usage, where the values are effectively constants, flags, "magic values" that keywords would be more idiomatic. (`"four of a kind"` can become `:four-of-a-kind`)

So instead of `"ones"` use `:ones`. And since keywords are unique you can then use `eq` to compare them. `case` might also work well here rather than `cond`.

2024-05-26 15:50 UTC, SimaDovakin commented on exercises/practice/yacht/.meta/example.lisp
> +  (cond ((equal category "ones") (count 1 scores))
I got it. Thank you! I'll change it.

2024-05-27 07:08 UTC, SimaDovakin commented
@verdammelt Now categories are keywords, and there is a `case` instead of `cond` in the main function.

2024-05-27 13:34 UTC, verdammelt approved these changes
Thank you for taking the time for all the updates.

2024-05-27 13:34 UTC, merged

2024-05-27 14:14 UTC, SimaDovakin commented
Thank you for all your reviews!